name: Binaries
on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: catalinii/minisatip-build-image:latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Build x64
      run: |
       ./configure --enable-static CC="clang -static" --disable-netcv
       make DDCI=1
       zip -9 -r /minisatip_x64.zip minisatip html

    - name: Build ARM
      run: |
       make clean
       ./configure --disable-netcv --enable-static --host=arm-linux-gnueabihf CC="clang -target arm-linux-gnueabihf -static"
       make
       zip -9 -r /minisatip_arm.zip minisatip html

    - name: Build AXE
      run: |
       make clean
       ./configure --disable-netcv --disable-dvbapi --enable-static --host=sh4-linux --disable-dvbca --enable-axe
       make PMT=0
       zip -9 -r /minisatip_axe.zip minisatip html

    - name: Build MIPS
      run: |
       make clean
       ./configure --disable-netcv --enable-static --host=mipsel-linux-gnu CC="zig cc -target mipsel-linux-gnueabihf.2.34 -static"
       make EXTRA_CFLAGS="-I/sysroot/mipsel/include -L/sysroot/mipsel/lib" EMBEDDED=1
       zip -9 -r /minisatip_mips.zip minisatip html


    - name: Bump version and push tag/create release point
      uses: anothrNick/github-tag-action@1.35.0
      if: ${{ github.event_name == 'push' && github.repository_owner == 'catalinii' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
      id: bump_version
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v1-release
      if: ${{ github.event_name == 'push' && github.repository_owner == 'catalinii' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /minisatip*zip
        file_glob: true
        tag: ${{ steps.bump_version.outputs.new_tag }}
        overwrite: true
