name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dvbcsa
      run: sudo apt-get install -y -f dvb-apps libdvbcsa-dev
    - name: configure
      run: ./configure
    - name: make
      run: make EXTRA_CFLAGS=-Werror
    - name: make test
      run: make test
