name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install -y -f libdvbcsa-dev libssl-dev
    - name: configure
      run: ./configure --with-mcli=/vdr-plugin-mcli/
    - name: make
      run: make EXTRA_CFLAGS=-Werror
    - name: make test
      run: make test
