name: Coverity Scan

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vapier/coverity-scan-action@v1
      with:
        project: minisatip2
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        email: reply+AB6SAEPNLEJSCE2WJ37GDNF6TC2NXEVBNHHDIEHQTY@reply.github.com
